### ISSUE TITLE
how to programmatic close popover

### ISSUE THREAD

**Issue by zwlcoding** [euvl/vue-js-popover#12]
thanks for you work

**Comment by euvl** [comment]
Hey, there is no way to close it programmatically , which is a shame :(

**Comment by ivantopo** [comment]
kind of hacky, but was able to programmatically close the popover by adding a ref to the popover in the template like this: 

```
<popover ref="popoverRef" ... >
....
</popover>
``` 

and then in the parent component doing `this.$refs.popoverRef.visible = false`. More info about this on the [Vue Guide](https://vuejs.org/v2/guide/components.html#Child-Component-Refs)

**Comment by msborrow** [comment]
> kind of hacky, but was able to programmatically close the popover by adding a ref to the popover in the template like this:
> 
> ```
> <popover ref="popoverRef" ... >
> ....
> </popover>
> ```
> 
> and then in the parent component doing `this.$refs.popoverRef.visible = false`. More info about this on the [Vue Guide](https://vuejs.org/v2/guide/components.html#Child-Component-Refs)

this.$refs.popoverRef.showPopper = false;
