### ISSUE TITLE
Is there a way to position tooltips?

### ISSUE THREAD

**Issue by quoid** [euvl/vue-js-popover#13]
One can position the popover like `<button v-popover:foo.right>button</button>`, but can we do something similar with tooltips?

Thanks for the plugin:)

**Comment by euvl** [comment]
Hey @quoid, 

Tooltip is a thin wrapper for popover.

```
<template>
  <popover name="tooltip"
           :pointer="pointer"
           :width="width"
           :event="event"
           @show="value = $event.value">
    {{value}}
  </popover>
</template>
<script>
export default {
  name: 'Tooltip',
  props: {
    event : { type: String, default: 'hover' },
    pointer: { type: Boolean,  default: false },
    width: { type: Number, default: 160 }
  },
  data () { return {  value: ''  } }
}
</script>
```

Thats the whole tooltip code. 
So if you need some extra functionality, it is very-very easy to create your own tooltip :)

**Comment by quoid** [comment]
Thanks @euvl, makes sense!
