### ISSUE TITLE
Popovers within v-for

### ISSUE THREAD

**Issue by diachedelic** [euvl/vue-js-popover#15]
I'm rendering a list of items, each with a little menu of its own (to go inside a Popover).

```html
<ul>
  <li v-for="item in group.items">
    ...
    <button v-popover:menu class="menu-toggle">Toggle</button>
    <popover name="menu">
      <button @click="duplicate(item)">Duplicate</button>
    </popover>
  </li>
</ul>
```

However I have the issue that selecting any of the toggles opens all the popovers (as they are all named 'menu').  Is there some way I can make each popover name unique?

**Comment by matbz** [comment]
What happens when you use :name="..." to make it dynamic?

**Comment by diachedelic** [comment]
It's more here: `<button v-popover:menu ...>` - how to I make 'menu' dynamic?

**Comment by voveson** [comment]
I have this same question. Let us know if you figure out a solution.

**Comment by euvl** [comment]
Yep, you can use this notation:

```
v-popover={ name: 'myname' }    instead of    v-popover.myname
```

**Comment by diachedelic** [comment]
Great! Works as of v1.1.5
