### ISSUE TITLE
How to enable transition?

### ISSUE THREAD

**Issue by hkrawczyk** [euvl/vue-js-popover#26]
Hello,

I have troubles with setting the transitions - it's not working at all for me. Any idea how can I use the one that are on exmaple page or on what class I should write own?

**Comment by euvl** [comment]
Don't know really what the proble can be, Just copy them from examples 😞

**Comment by demiavaliani** [comment]
@euvl  This is really not helpful. You have a good mini library that does one specific thing which is great. I would advise having full documentation. This issue is still active, as I didn't find any examples of how to use transitions.
