### ISSUE TITLE
vue-is-popover prevent dropdown menu to open

### ISSUE THREAD

**Issue by GMounir** [euvl/vue-js-popover#29]
I'm using bootstrap dropdown menu with popover.

- bootstrap using click event to show list (by default jquery)
- popover using hover to show message 

but popover prevent dropdown to show
Please how to solve this problem
Thank you.

**Comment by tm2josep** [comment]
Using jquery with vue is frowned upon. Try using a vue based dropdown.

**Comment by euvl** [comment]
Yeah ⬆️
