### ISSUE TITLE
Dynamic names

### ISSUE THREAD

**Issue by cdarken** [euvl/vue-js-popover#3]
I don't think there's a way to make binding.arg dynamic in case you want to display a popover for each item in a list for instance. Or if it is I don't know how to use it. Do you have any advice?

**Comment by euvl** [comment]
Currently it is all static. I have some ideas how I might make it more agile but for now yeah, static. 

Not sure if it will work but you can try this setup:

```
<button v-popover:tooltip @click="tooltip = 'message'">Show</button>
<popover name="tooltip">{{message}}</popover>
...

export default {
  data () { message: '' }
}

**Comment by cdarken** [comment]
Why didn't you use the value for the name? It can be also an object AFAIK. Anyway, thanks for your suggestion, I will try to implement it like you suggested. But I will need to create a mechanism to hide the open popover when another one is shown.
Feel free to close this or leave it open for future reference until something dynamic is implemented. Thanks.

**Comment by euvl** [comment]
`Why didn't you use the value for the name? ` - dont like double qoutes `v-popover="'name'"`.
`But I will need to create a mechanism to hide the open popove` - Well, it is open source, and i asume you get paid for your work, so cant do all the work for you.

**Comment by cdarken** [comment]
Sorry if I sounded pretentious but I was trying to throw out ideas. I know it's open source, didn't mean to imply you should do the work for me.

**Comment by euvl** [comment]
No worries. I was a bit to aggressive. Sorry.

**Comment by cdarken** [comment]
No problem. You're doing great work. When I have time I will fork it and try to make a pull request.
