### ISSUE TITLE
popover name can be dynamic ?

### ISSUE THREAD

**Issue by vbalasubramani** [euvl/vue-js-popover#30]
`<div v-popover:{{detail.id}} class="g-match-list" >
                        <h1>LIVE</h1>
                        <label>{{detail.period}}</label>
                        <span>{{detail.name}}</span>
                        <popover v-bind:name = "detail.id">
                            Hello
                         </popover>
          </div>`

Popover name can be dynamic ?

**Comment by diachedelic** [comment]
See #15
