### ISSUE TITLE
Getting hover working

### ISSUE THREAD

**Issue by erichodges** [euvl/vue-js-popover#35]
I would like to have the popup work on hover. I don't understand how to use the props code:

```
props: {
  /* Tooltip name.                           */
  name:    { type: String,  required: true   },
  
  width:   { type: Number,  default: 180     },
  
  /* If set - will show a tiny tip.          */
  pointer: { type: Boolean, default: true    },
  
  /* Name of the event which triggeres 
     showing/hiding of the popover.
     Possible values are: 'click', 'hover'.  */  
  event:   { type: String,  default: 'click' }
}
```
I tried several different permutations. Is the above props only for the Tooltip option? I'm using Nuxt. I was able to get the popup to work on click. 

I also noticed that if I change the width of the popup via css, the popup is no longer centered. Is there a way around this?

**Comment by erichodges** [comment]
Thank you. I just figured out that I have to also enter event="hover" in the <popover> tag, along with anything else that I want, such as width.

When using hover, it's very difficult to select from the popup. As I move the mouse down to select, the popup disappears. Is there a solution for this?

**Comment by erichodges** [comment]
I'm getting a warning from Vue for an invalid prop when I use width in <popover>:

`<popover name="ccc" event="hover" width=100>`

The error says that it expected a number and got a string, but I used a number in both the anchor tag and the <popover> tag.

**Comment by euvl** [comment]
` width=100>` is neither valid html no vuejs

**Comment by euvl** [comment]
Try `:width="100"`

**Comment by erichodges** [comment]
That crashes the app.

**Comment by euvl** [comment]
I don't know then ¯\_(ツ)_/¯

**Comment by erichodges** [comment]
Ok thank you :-)
