### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by seekcx** [euvl/vue-js-popover#4]
Hope to add SSR support for this component, just like modal.😁

**Comment by euvl** [comment]
Yeah @seekcx, i will try to spend some time on it on the upcoming weekend

**Comment by cihadturhan** [comment]
I can use popover inside `<no-ssr>` tag in nuxt without issues. Thanks for the plugin

**Comment by euvl** [comment]
No worries! Also tbh i see no reason to use this plugin with ssr 😄
