### ISSUE TITLE
Position is not correct

### ISSUE THREAD

**Issue by akaNightmare** [euvl/vue-js-popover#5]
As I understand top and left calculating from body position, but what if parent DOM element has position absolute or relative http://screenshots.client-demo-site.net/scn-20170712-092042-6c373.png

**Comment by euvl** [comment]
Hey @akaNightmare,

Positioning should be fixed in `v1.1.2`.
Let me know if you will have any further issues with the plugin  👍

**Comment by akaNightmare** [comment]
@euvl great job 👍
