### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of undefined"

### ISSUE THREAD

**Issue by akaNightmare** [euvl/vue-js-popover#6]
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'getBoundingClientRect' of undefined"

found in

**Comment by euvl** [comment]
Thanks for reporting but could you be more constructive please.

Might happen when, for example, if you use hot reload and the button is rerendered while popover is active. Can by anything tbh 😉

**Comment by euvl** [comment]
Fixed
