### ISSUE TITLE
Width is incorrect

### ISSUE THREAD

**Issue by akaNightmare** [euvl/vue-js-popover#7]
http://screenshots.client-demo-site.net/scn-20170712-190027-a72s6.png

**Comment by euvl** [comment]
What?

**Comment by akaNightmare** [comment]
@euvl oh, I see width should be added manually.

**Comment by euvl** [comment]
![Uploading Screen Shot 2017-07-12 at 17.24.07.png…]()
<img width="317" alt="screen shot 2017-07-12 at 17 24 12" src="https://user-images.githubusercontent.com/1577802/28128237-fd8aecdc-6726-11e7-9eb2-b5a37b0963dd.png">

**Comment by euvl** [comment]
Yep, take a look in readme and examples for more info 👍
