### ISSUE TITLE
overflow question

### ISSUE THREAD

**Issue by lukeo3o1** [euvl/vue-js-popover#9]
first , this is a great component.
but i got a question.

in a list , 
I don't want to the items are very many and the list is so long.
and i set `overflow: auto;` and set the list `max-height: 500px;`,

so question is here
<img width="549" alt="2017-07-23 11 45 46" src="https://user-images.githubusercontent.com/19261836/28500836-39462d48-7002-11e7-93d0-fc9797aad37a.png">

the Popover will not on true position.

Is there any way to solve it?

I think `getDrodownPosition()` is get the hide item's position

Thank you!!!!

**Comment by euvl** [comment]
Hey,thanks.

Could you please clarify what the problem is, I am afraid I did not understand what you were trying to say.

Or better, create a jsfiddle 😄 👍

**Comment by lukeo3o1** [comment]
[`like this`](https://youtu.be/AwoRPSkYywE) 
Thank you

**Comment by euvl** [comment]
I dont think you will be able to achieve required behaviour with the current implementation of the plugin 😞

**Comment by lukeo3o1** [comment]
ok i got it.
I will find other way achieve my question.
thank you 😄

**Comment by euvl** [comment]
No probs, I'll take bit closer look this week.

You will probably want your tooltip be a sibling of the list item btw. This way you will be able to get smooth scrolling.. otherwise if you will be using javascript to recalculate position you might get glitchy animation 👍

**Comment by lukeo3o1** [comment]
I found the solution to my question,

[https://jsfiddle.net/9h05g8L3/](url)

but it is simple and crude.
thank you for your suggestion👍!!

**Comment by euvl** [comment]
Cool, looks great! 👍
